### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by LordMike** [LordMike/TMDbLib#199]
@Naliath .. have you had a look at the project lately? I've dedicated a bit of time over the last few weeks, and I've squared off a number of the outstanding issues.

We've always had the issue of checking if our objects match the response, and previously we went the tedious road of fact checking every property (and adjusting when the source changes). I've set up a system that automatically validates properties, by letting Newtonsoft inform us when it's missing something either on the C# end or the JSON end.. This is in place now, and will alert you when you run the tests.

@dancooper @tidusjar .. could you check out the latest alpha builds on Nuget and see if they still work on your end?.. A number of API's have changed, so there may be some issues there.. Just checking :)

**Comment by Naliath** [comment]
@LordMike yea been follow8ng along but between work and the familly there has not been much time left over :). If there is something specific you would like a second opinion on or something I can implement just ping me and I'll find some time

**Comment by LordMike** [comment]
No specifics - just wondering if it all works or if I'm in my own little happy bubble :P

**Comment by tidusjar** [comment]
@LordMike when you sAy API changes, is there any breaking changes or a change log?

**Comment by LordMike** [comment]
There will be some breaking changes, but they should all be handle-able. Most of them stem from the fact that TMDb have removed properties on their objects (which I've accounted for). The Changelog is incomplete, but I've tried to keep it updated (it's in the Readme).

All methods should work as they did before - that is, if it still compiles, nothing should have changed. :)

**Comment by ebadola** [comment]
Hi guys I have problem  when i get movie 

thi is code

            TMDbLib.Client.TMDbClient cl = new TMDbLib.Client.TMDbClient("ApiKey");

                TMDbLib.Objects.Movies.Movie movie = cl.GetMovieAsync(47964).Result;

an error


(Inner Exception #0) Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at TMDbLib.Rest.RestResponse`1.<GetDataObject>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TMDbLib.Client.TMDbClient.<GetMovieAsync>d__121.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TMDbLib.Client.TMDbClient.<GetMovieAsync>d__120.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TMDbLib.Client.TMDbClient.<GetMovieAsync>d__118.MoveNext()<---

**Comment by tidusjar** [comment]
Upgrading from `0.9.0-alpha` to `0.9.6-alpha` we now have a dependency on System.Net.Http?

**Comment by LordMike** [comment]
@ebadola that looks like you received not-json from TMDb.. As in something with XML.. Can you possibly intercept (like with Fiddler) and see what's going on?

@tidusjar yes - the entire client is now Async. All methods were back then renamed to *Async to ensure that A) You realize the change and B) if we ever do Sync counterparts it wouldn't break in the future. If you append a `.Result`, you'll get the sync version pretty quickly.

`GetMovieList` is one of the last things I've done. I realized that two of the four possible methods also returned a date range "dates". So to reduce confusion I've split them into four methods - and yes, you are correct. The new method names match the previous enum values.

What returned `MovieResult` (I can't recall).. If you look at the methods you're using, you'll see what they return. I've been shuffling a bit around to better match what TMDb returns. I've discovered that TMDb generally has two types for each data item (Movie, TvShow, Person, ..). They have a full edition (with all the properties) and a lighter "search" edition which appears when you search for stuff.

So it's very likely that `MovieResult` was previously part of a search result, which is now `SearchMovie`.

**Comment by LordMike** [comment]
@tidusjar reg. the Net.Http. We moved away from RestSharp which has its own network connection/HTTP stuff - but without it we needed two things: Json serializer and HTTP clients. Instead of using WebRequest we opted to use HttpClient which is available in most platforms - just not some, such as Core.

If absolutely necessary, we *could* go over to Webrequest.. I don't think it will affect anything, as it too has awaitable Async calls.

**Comment by tidusjar** [comment]
@LordMike Thanks for the reply. I was just wondering why, using WebRequest over HttpClient doesn't affect me in anyway :)

If you are curious to see what I am using your library for: github.com/tidusjar/RequestPlex

**Comment by LordMike** [comment]
@tidusjar I noticed from other issues that you mentioned it there too. Let me know how it turns out :)

**Comment by tidusjar** [comment]
How's the release looking?

**Comment by LordMike** [comment]
Well. I'm always on the conservative side, always thinking what-if. 
But if the current 0.9.6 works, then we could push that to 1.0.

**Comment by LordMike** [comment]
ae4572713c942c8d6cd27b6fc80a1d4543dcc1a9
