### ISSUE TITLE
Could not convert 'destroyed' to ChangeAction breaking change

### ISSUE THREAD

**Issue by agoretsky** [LordMike/TMDbLib#211]
Hello!
try `await tmdbClient.GetMovieChangesAsync(435470, new DateTime(2017, 1, 17));`

```
Newtonsoft.Json.JsonSerializationException: Error converting value "destroyed" to type 'TMDbLib.Objects.Changes.ChangeAction'. Path 'action', line 1, position 177. ---> System.ArgumentException: Requested value 'destroyed' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)}
```

**Comment by agoretsky** [comment]
`await tmdbClient.GetTvShowChangesAsync(1920)`

![destroyed1](https://cloud.githubusercontent.com/assets/17613086/22106948/4f8a06d4-de5c-11e6-9533-cc137ed4ca6d.png)

`await tmdbClient.GetMovieChangesAsync(435470, new DateTime(2017, 1, 17));`

![destroyed2](https://cloud.githubusercontent.com/assets/17613086/22106961/5e520a18-de5c-11e6-843d-ae9d94b8fb91.png)

**Comment by LordMike** [comment]
And one wonders what the difference of Destroyed and Deleted is ....

**Comment by LordMike** [comment]
@agoretsky do you know of any documentation for this?

It seems the value could be a dictionary of String->JToken og String->String

**Comment by agoretsky** [comment]
No, I don't

**Comment by agoretsky** [comment]
@LordMike Could you please publish version with this fix to nuget?

**Comment by LordMike** [comment]
I just did. It's `1.0.4-alpha`.

**Comment by agoretsky** [comment]
Thanks
