### ISSUE TITLE
await _tmdbClient.GetPersonAsync(x) results in A task was canceled

### ISSUE THREAD

**Issue by hgirma** [LordMike/TMDbLib#262]
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TMDbLib.Rest.RestRequest.<SendInternal>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TMDbLib.Rest.RestRequest.<ExecuteGet>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TMDbLib.Client.TMDbClient.<GetPersonAsync>d__153.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TalakFilm.Parser.MovieDetail.<GetCredits>d__17.MoveNext()

**Comment by LordMike** [comment]
This is likely a timeout. Are you experiencing long response times?

**Comment by hgirma** [comment]
No not really, but it happens sporadically. Not sure how to handle it gracefully.

**Comment by LordMike** [comment]
It's most likely a timeout. The library should attempt retries to a certain extent (https://github.com/LordMike/TMDbLib/blob/master/TMDbLib/Rest/RestRequest.cs#L194-L236). You can attempt to raise the `MaxRetryCount` from 0 to something more.
