### ISSUE TITLE
NotImplementedException when serializing a collection of SearchMovie

### ISSUE THREAD

**Issue by D4N3-777** [LordMike/TMDbLib#268]
When I try to serialize a collection of SearchMovie i get this exception.

Partial stacktrace:
`{System.NotImplementedException: The method or operation is not implemented.
   at TMDbLib.Utilities.Converters.SearchBaseConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer) in E:\Mike\Projects\TMDbLib\TMDbLib\Utilities\Converters\SearchBaseConverter.cs:line 55
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Din.Controllers.ContentController.SearchMovie() in C:\Users\Dane\Documents\git_projects\Din\src\Din\Controllers\ContentController.cs:line 19
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()}`

**Comment by D4N3-777** [comment]
i see the issue is fixed in the latest pre-reelease v1.1.0-alpha. I'll move away from using the nuget version.

**Comment by LordMike** [comment]
You could use that specific version :)

Also - there is a 1.2.0-alpha out.
