### ISSUE TITLE
JSON integer 5185860891 is too large or small for an Int32. Path 'last_episode_to_air.episode_number

### ISSUE THREAD

**Issue by TheUltimateC0der** [LordMike/TMDbLib#358]
TV Show Id: 105941

```
Newtonsoft.Json.JsonReaderException: JSON integer 5185860891 is too large or small for an Int32. Path 'last_episode_to_air.episode_number', line 1, position 368.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at TMDbLib.Rest.RestResponse`1.GetDataObject()
   at TMDbLib.Client.TMDbClient.GetTvShowAsync(Int32 id, TvShowMethods extraMethods, String language, String includeImageLanguage, CancellationToken cancellationToken)
```

**Comment by LordMike** [comment]
Seems like a data issue in the database.. It's unlikely there's an episode with that number.

**Comment by LordMike** [comment]
Fark me

https://www.themoviedb.org/tv/105941-khalls-ali-braim/season/1/episode/5185860891

![image](https://user-images.githubusercontent.com/1027111/105638691-56c68480-5e74-11eb-8b68-3511d1e91708.png)

**Comment by LordMike** [comment]
@TheUltimateC0der you can report this to TMDb on their forums.. Let us know if it's intentional.

**Comment by LordMike** [comment]
https://www.themoviedb.org/talk/600dc5022a210c00419cc6c1

**Comment by LordMike** [comment]
Fixed serverside.
