### ISSUE TITLE
NullReference from the library from Rest.RestResponse.Dispose()

### ISSUE THREAD

**Issue by SirSparkles** [LordMike/TMDbLib#405]
Recently there has been a flurry of NREs coming out of the interface. All from the Dispose() method:

TMDB:929282 [Halo: The Fall of Reach] 

System.NullReferenceException: Object reference not set to an instance of an object.
     at TMDbLib.Rest.RestResponse.Dispose()
     at TMDbLib.Client.TMDbClient.<GetMovieAsync>d__140.MoveNext()

  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at TMDbLib.Client.TMDbClient.<GetMovieAsync>d__139.MoveNext()

**Comment by SirSparkles** [comment]
System.AggregateException: One or more errors occurred. ---> 
System.NullReferenceException: Object reference not set to an instance of an object.
     at TMDbLib.Rest.RestResponse.Dispose()
     at TMDbLib.Rest.RestRequestExtensions.<GetOfT>d__1`1.MoveNext()

  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at TMDbLib.Client.TMDbClient.<GetTvShowMethodInternal>d__218`1.MoveNext()

  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at TMDbLib.Client.TMDbClient.<GetTvShowRecommendationsAsync>d__238.MoveNext()

     --- End of inner exception stack trace ---  ---> 
(Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
     at TMDbLib.Rest.RestResponse.Dispose()
     at TMDbLib.Rest.RestRequestExtensions.<GetOfT>d__1`1.MoveNext()

  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at TMDbLib.Client.TMDbClient.<GetTvShowMethodInternal>d__218`1.MoveNext()

  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at TMDbLib.Client.TMDbClient.<GetTvShowRecommendationsAsync>d__238.MoveNext()

<---    ---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
     at TMDbLib.Rest.RestResponse.Dispose()
     at TMDbLib.Rest.RestRequestExtensions.<GetOfT>d__1`1.MoveNext()

  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at TMDbLib.Client.TMDbClient.<GetTvShowMethodInternal>d__218`1.MoveNext()

  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at TMDbLib.Client.TMDbClient.<GetTvShowSimilarAsync>d__236.MoveNext()

<---

**Comment by carlosmanri** [comment]
I have the same issue. 

System.NullReferenceException
  HResult=0x80004003
  Mensaje = Object reference not set to an instance of an object.
  Origen = TMDbLib
  Stack trace:
   at TMDbLib.Rest.RestResponse.Dispose()
   at TMDbLib.Client.TMDbClient.<GetTvSeasonAsync>d__213.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
...

**Comment by carlosmanri** [comment]
I just realized that checking if its null before disposing the response in RestResponse.Dispose() solves the problem. I dont know why is getting disposed before that.

```c#

        [SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP007:Don't dispose injected.", Justification = "RestResponse owns the response")]
        public virtual void Dispose()
        {
            Response?.Dispose(); // <--there
        }
```

**Comment by LordMike** [comment]
I have pushed `1.9.2` which includes the null check proposed by @carlosmanri - hope this works out for all of you :)
