### ISSUE TITLE
Small changes from TMDb cause bug

### ISSUE THREAD

**Issue by uponatime2019** [LordMike/TMDbLib#411]
`https://api.themoviedb.org/3/trending/movie/Week?api_key=`
will cause a request error
`{"success":false,"status_code":5,"status_message":"Invalid parameters: Your request parameters are incorrect."}`

`Week` should lower case to make api working

**Comment by benjimola** [comment]
I was struggling with this wondering why it is not working. thank you.

**Comment by SirSparkles** [comment]
Might be the same issue I am seeing?

TMDbLib.Objects.Exceptions.GeneralHttpException: TMDb returned an unexpected HTTP error
   at TMDbLib.Rest.RestRequest.SendInternal(HttpMethod method, CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequest.Get[T](CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequestExtensions.GetOfT[T](RestRequest request, CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.GetTrendingMoviesAsync(TimeWindow timeWindow, Int32 page, CancellationToken cancellationToken)

**Comment by SirSparkles** [comment]
I have done a quick fix at: https://github.com/LordMike/TMDbLib/pull/416/files

**Comment by SirSparkles** [comment]
Can we release this fix please?
